packages:
  - .
  - apps/*
  - packages/*
allowBuilds:
  '@sentry/cli': true
  better-sqlite3: true
  electron: true
  esbuild: true
  sharp: true
  spawn-sync: true
fetchRetries: 5
networkConcurrency: 3
